language: python
matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
#    - env: TOXENV=pep8
# command to install dependencies
install: "pip install tox"
# command to run tests
script: tox
